apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: thanos
type: Opaque
stringData:
  alertmanager.yaml: |-
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_interval: "5m" #time interval to sent again
      group_wait: "30s" #after sent wait time
      receiver: "send2sms" #default receiver
      repeat_interval: "3h"   # If an alert has successfully been sent, wait 'repeat_interval' to resend them.
      routes:
      - match :
          severity: 'critical'
        receiver: 'send2msteam'
        continue: true
      - match :
          severity: 'critical'
        receiver: 'send2fm'
        continue: true
      - match :
          severity: 'critical'
        receiver: 'send2sms'
    receivers:
      - name: teams
        webhook_configs:
        - send_resolved: true
          url: 'https://webhook.site/94fe664b-163c-4dae-b1b0-cd252633a1db' 
      - name : 'send2sms'
        webhook_configs:
        - url: 'http://prom-adapter-service.notification/apis/sms/v1'
          send_resolved: true
      - name : 'send2msteam'
        webhook_configs:
        - url: 'http://prom-adapter-service.notification/apis/msteam/v1'
          send_resolved: true
      - name : 'send2fm'
        webhook_configs:
        - url: 'http://prom-adapter-service.notification/apis/fm/v1'
          send_resolved: true