apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: thanos
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "receivers":
    - "name": "Default"
    - "name": "Watchdog"
    - "name": "Critical"
    - name: 'gmail_notifications'
      email_configs:
      - to: kittisuw@gmail.com
        from: kittisuw@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: kittisuw@gmail.com
        auth_identity: kittisuw@gmail.com
        auth_password: btymhuryhputoisa
        send_resolved: true
    "route":
      "group_by":
      - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "Default"
      "repeat_interval": "12h"
      "routes":
      - "match":
          "alertname": "Watchdog"
        "receiver": "gmail_notifications"
      - "match":
          "severity": "critical"
        "receiver": "Critical"
type: Opaque
