kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: thanos
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi