apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-sidecar
    prometheus: k8s
  name: prometheus-k8s-thanos-sidecar
  namespace: thanos
spec:
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "foo.local"
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  selector:
    app: prometheus
    prometheus: k8s
