apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-thanos-query
  namespace: monitoring
  labels:
    release: prom-op
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: thanos-query
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: http-query
    interval: 15s