apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-store-config
  namespace: monitoring
data:
  thanos-store.yml: |-
    type: S3
    config:
      bucket: ankercloud-stg-monitoring
      endpoint: "s3.ap-south-1.amazonaws.com"
      access_key: <AccessKey>
      secret_key:<SecretKey>
      insecure: false
      signature_version2: false
      encrypt_sse: true
      http_config:
          idle_conn_timeout: 0s