type: s3
config:
  bucket: mysolos #S3 bucket name
  endpoint: s3.ap-east-1.amazonaws.com #S3 Regional endpoint
  access_key: AKIAIQBGARN4RQDJWYBQ
  secret_key: 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
  #encryptsse: true
