apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-ruler-rules
  namespace: thanos
data:
  alert_InstanceDown.rules.yaml: |
    groups:
        - name: natthasw_ex
          rules:

          # Alert for test.
          - alert: InstanceDown
            expr: grafana_api_models_dashboard_insert_total < 50
            for: 5s
            labels:
                severity: critical
            annotations:
                module: '{{ $labels.job }}'
                amoName: '{{ $labels.pod }}'
                alarmName: 'InstanceDown'
                description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 sec."
                node: '{{ $labels.job }}'
                systemName: '{{ $labels.service }}'
                emsName: '{{ $labels.pod }}'
                mcZone: ''
                emsIp: '{{ $labels.instance }}'
                siteCode: '{{ $labels.pod }}'
                severity: 'critical'
                region: BKK
                nodeIp: '{{ $labels.instance }}'
                networkType: VTOP
                msteamUrl: 'https://outlook.office.com/webhook/fd5b48e7-d8ac-4b17-ae4c-02647856d040@833df664-61c8-4af0-bcce-b9eed5f10e5a/IncomingWebhook/368188ddbc6a4ae99f8e7256b96e2220/b37a0e68-660d-4fab-93f5-f414552ef720'
